#!/usr/bin/env sh
#. "$(dirname -- "$0")/_/husky.sh"

#npm test
TEST_EXIT_CODE=$?

if [ $TEST_EXIT_CODE -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
else
  echo "Tests passed. Commit allowed."
fi

